---
title: "keepers_visualization"
author: "Toby Chiu"
date: "2023-07-23"
output: html_document
---

We are trying to visualise 

## Basic Setup

```{r}
library(tidyverse)
library(plotly)
library(htmlwidgets)
```


```{r}
overall_data <- read.csv("C:/Users/tobyt/Desktop/Coding/Personal/wins-above-replacement-soccer/WAR-based-soccer-valuation/output/PCA/overall_keepers_war.csv")
```
```{r}
overall_data <- overall_data %>% 
  drop_na("player_market_value_euro")
```

```{r}
plot <- ggplot(data=overall_data, mapping=aes(x=calculated_war, y=player_market_value_euro, label = unique_ID)) + geom_point() + geom_smooth() + geom_text_repel()
```

```{r}
plot <- ggplotly(plot)
plot
```
```{r}
saveWidget(widget = plot, 
           file = "C:/Users/tobyt/Desktop/Coding/Personal/wins-above-replacement-soccer/WAR-based-soccer-valuation/img/keepers-overall-test.html", 
                selfcontained = TRUE #creates a single html file
                )
```



```{r}
plot_ly(data = overall_data, x = ~calculated_war, y = ~player_market_value_euro) %>% 
  add_trace(
    type = 'scatter',
    mode = 'markers',
    text = ~unique_ID, # when you hover on a point it will show it's rowname
    hoverinfo = 'text',
    showlegend = F
  ) + add_lines(line= list(shape='spline', smoothing=1.3))
```

